### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by diamondap** [krpors/dom#1]
In the code example on your README page, this:

	builder := dom.NewBuilder(resp.Body)
	doc, err := builder.Parse()

Should actuall say this:

    parser := dom.NewParser(resp.Body)
    doc, err := parser.Parse()

Good work overall. Thanks for writing this!

**Comment by krpors** [comment]
Hey thanks. I appreciate your interest in the library! I haven't updated things in a while. I tested some stuff a month ago and even though the navigation through the document goes well, outputting it does not work 100%. So be careful :) If you find anything, let me know.

**Comment by diamondap** [comment]
Thanks. I was just experimenting. I'm not planning on using it for anything mission-critical, but I'll let you know if I run into issues.
